name: android-tests

on:
  workflow_dispatch:
  push:
    branches:
      - ubuntu-android-tests

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: haskell
      run: |
        ghc --version
        stack --version
        cabal --version
        
    - name: Test
      run: |
        export INSTALLER_SCRIPT_FOLDER="."
        pwsh -Command "Invoke-Pester"
