name: android-tests

on:
  workflow_dispatch:
  push:
    branches:
      - ubuntu-android-tests

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: create symlink
      run: |
        sudo ln -s test.sh /usr/bin
        ls -la /usr/bin
        
    - name: Pester
      run: |
        bash mssql-cmd-tools.sh
