name: android-tests

on:
  workflow_dispatch:
  push:
    branches:
      - ubuntu-android-tests

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: create symlink
      run: |
        chmod -x ./gogo/invoke_tests.sh
        sudo ln -s /home/runner/work/test-repo/test-repo/gogo/invoke_tests.sh /usr/local/bin
        
    - name: check /usr/local/bin
      run: pwd
        
    - name: Pester
      run: |
        bash mssql-cmd-tools.sh
