name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Check packages
      run: |
        pip3 list
        
    - name: Install pipx
      run: |
        sudo apt-get install python3-venv
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        echo "::add-path::/home/runner/.local/bin"
        
    - name: Install django default python
      run: |
        pipx --version
        pipx run https://github.com/vsafonkin/test-repo/blob/master/hello.py
        pipx install django
        
    - name: Check pip packages
      run: |
        pip3 list
        
    - name: Uninstall django
      run: |
        pipx uninstall django
        
    - name: Setup Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.7.x

    - name: Install django python 3.7
      run: |
        pipx install django

    - name: Check pip packages
      run: |
        pip3 list
    
    - name: Uninstall django
      run: |
        pipx uninstall django
        
    - name: Setup Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.8.x
        
    - name: Install django python 3.7
      run: |
        pipx install django

    - name: Check pip packages
      run: |
        pip3 list
        
