name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set SDKROOT
      run: echo "::set-env name=SDKROOT::C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk"
  
    - name: Install Swift
      run: |
        pwsh ./Test.ps1 
      
    - name: Check version
      run: swift --version
        

