name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    
    - name: Ruby toolcache
      run: |
        ls $AGENT_TOOLSDIRECTORY/ruby
    
    - name: Clone ruby-install
      run: git clone https://github.com/postmodern/ruby-install.git
    
    - name: Install ruby-install
      run: sudo make install
      working-directory: ./ruby-install

    - name: List versions
      run: ruby-install

    - name: Help
      run: ruby-install --help


