name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        $Url = "https://www.microsoft.com/en-us/download/confirmation.aspx?id=7030"
        (New-Object System.Net.WebClient).DownloadFile($Url, "C:\\vb6.msi")
        $ArgumentList = ('/i', 'C:\\vb6.msi', '/QN', '/norestart')
        $filePath = "msiexec.exe"
        $process = Start-Process -FilePath $filePath -ArgumentList $ArgumentList -Wait -PassThru
        Write-Host $process.ExitCode
