name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: ssh
      run: |
        git clone git@github.com:vsafonkin/test-pip-tensorflow.git

    - name: Test
      run: |
        pwsh ./Test.ps1


