name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Help
      run: |
        nuget version
        nuget help
        
    - name: Test
      run: |
        nuget version



