name: Test CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: makensis --version
      run: makensis --version
    
    - name: Test.ps1
      run: pwsh ./Test.ps1


