name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        node --version
        . ~/.bashrc
        nvm install 10.5.0
        nvm alias default 10.5.0
        node --version
