name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install pipx
      run: |
        python3 --version
        pip3 list
        echo "-----------"
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        echo "-----------"
        pip3 list
        

