name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Find ninja
      run: where /r C:\ ni*.exe
      shell: cmd
    
    - name: Set SDKROOT
      run: |
        echo "::set-env name=SDKROOT::C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk"
        echo "::add-path::C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin"
  
    - name: Install Swift
      run: |
        pwsh ./Test.ps1 
      
    - name: Check version
      run: swift --version
    
    - name: Test build
      run: |
        git clone git://github.com/compnerd/swift-cmake-examples C:\swift-cmake-examples
        $SWIFTFLAGS="-sdk $env:SDKROOT -resource-dir $env:SDKROOT/usr/lib/swift -I $env:SDKROOT/usr/lib/swift -L $env:SDKROOT/usr/lib/swift/windows"
        cmake -B "C:\HelloWorld" -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -D CMAKE_Swift_FLAGS=$SWIFTFLAGS -G "Ninja" -S "C:\swift-cmake-examples\HelloWorld"
        cmake --build C:\HelloWorld
        

