name: Test CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-2016, windows-2019 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Path
      run: $env:Path
    
    - name: Install ms sql command line utils
      run: |
        choco install sqlserver-cmdlineutils
        echo "::add-path::C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn"
        
    - name: Path
      run: $env:Path
    
    - name: Run SQL Server
      run: |
        pwsh Test.ps1


