name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: ssh-keyscan
      if: ${{ always() }}
      run: |
        dig +short github.com
        echo "-----"
        ssh-keyscan -t rsa github.com
        echo "-----"
        ssh-keyscan -t rsa gist.github.com
        echo "-----"
    
    - name: ssh
      if: ${{ always() }}
      run: |
        git clone git@github.com:vsafonkin/test-pip-tensorflow.git
    
    - name: known hosts
      if: ${{ always() }}
      run: |
        ls .ssh
        
    - name: Test
      run: |
        pwsh ./Test.ps1


