name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.7.x

    - name: Install pipx
      run: |
        python3 --version
        pip3 list
        echo "-----------"
        echo "::add-path::/home/runner/.local/bin"
#        python3 -m pip install --user pipx
#        python3 -m pipx ensurepath

    - name: install pip-compile
      run: |
        pip3 install --user pip-compile
        echo "-------"
        pip3 list
        pip-compile --version
    
    - name: Setup Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.8.x
        
    - name: Check pip-compile
      run: |
        pip3 list
        pip-compile --version
        
    - name: Check bin
      run: ls /home/runner/.local/bin
