name: Test CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    
    - name: env
      run: env
    
    - name: show PATH
      run: echo $PATH
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    
    - name: env
      run: env
    
    - name: Ruby version
      run: |
        ruby --version
        which ruby
      
    - name: Ruby toolcache
      run: |
        ls $AGENT_TOOLSDIRECTORY/Ruby/2.7.1/x64/lib
        
    - name: show PATH
      run: echo $PATH
      
    - name: run Test.ps1
      run: sudo pwsh ./Test.ps1
    
    - name: Show .gemrc
      run: cat $HOME/.gemrc


