name: Test CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-18.04, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: env
      run: env
    
    - name: Test.ps1
      run: sudo pwsh ./Test.ps1


