name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: GHC
      run: |
        cd sample
        ghc Main.hs --make -o sample

    - name: Test Cabal
      run: |
        cabal --version
        cd sample
        cabal update
        cabal install haskell-say
        cabal build
        cabal run
    
    - name: Test Stack
      run: |
        stack new sample-stack new-template
        cd sample-stack
        stack setup
        stack build
        stack exec sample-stack-exe
        stack test
