name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: test.sh
      run: |
        bash test.sh

    - name: Test.ps1
      run: |
        pwsh ./Test.ps1
