name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: ssh-keyscan
      if: ${{ always() }}
      run: |
        dig +short github.com
        echo "-----"
        ssh-keyscan -t dsa github.com
        echo "-----"
        cat /etc/ssh/ssh_known_hosts
    
    - name: ssh
      if: ${{ always() }}
      run: |
        ssh -v localhost
        
    - name: Test
      run: |
        pwsh ./Test.ps1


