name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set SDKROOT
      run: echo "::set-env name=SDKROOT::C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk"
  
    - name: Install Swift
      run: |
        pwsh ./Test.ps1 
      
    - name: Test build
      run: |
        mkdir %SystemDrive%/SourceCache
        mkdir %SystemDrive%/BinaryCache
        git clone git://github.com/compnerd/swift-cmake-examples %SystemDrive%/SourceCache/swift-cmake-examples
        set SWIFTFLAGS=-sdk %SDKROOT% -resource-dir %SDKROOT%/usr/lib/swift -I %SDKROOT%/usr/lib/swift -L %SDKROOT%/usr/lib/swift/windows
        "%ProgramFiles%/CMake/bin/cmake.exe"      ^
          -B %SystemDrive%/BinaryCache/HelloWorld ^
          -D BUILD_SHARED_LIBS=YES                ^
          -D CMAKE_BUILD_TYPE=Release             ^
          -D CMAKE_Swift_FLAGS="%SWIFTFLAGS%"     ^
          -G Ninja                                ^
          -S %SystemDrive%/SourceCache/swift-build-examples/HelloWorld-CMake
        cmake --build %SystemDrive%/BinaryCache/HelloWorld
      shell: cmd
        

