name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    
    - name: Help
      run: |
        apt list
    
    - name: Test
      run: |
        flex -v sample.lex
        bison -vdt bisonparser.y
        cc -v lex.yy.c bisonparser.tab.c -o bisonsample
        echo "-----------------------------"
        ls .
        echo "-----------------------------"
        ./bisonsample
        22+3*4-5



