name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        php7.1 --version
        php7.2 --version
        php7.3 --version
        php7.4 --version
        



