name: Test CI

on:
  workflow_dispatch:
    inputs:
      subscriptionID:
        description: 'Azure subscription id'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Check PS modules
      run: ls C:\Modules\az_4.6.0
    - name: Test
      run: |
        git clone https://github.com/actions/virtual-environments.git
        cd $PWD\virtual-environments
        Import-Module "$PWD\helpers\GenerateResourcesAndImage.ps1"
        Import-Module "C:\Modules\az_4.6.0"
        GenerateResourcesAndImage -SubscriptionId ${{ github.event.inputs.subscriptionID }} -ResourceGroupName "v-vlsafo" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1604 -AzureLocation "East US" -GithubFeedToken ${{secrets.GITHUB_TOKEN}}


