name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.7.x

    - name: Install pipx
      run: |
        python3 --version
        pip3 list
        echo "-----------"
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        echo "::add-path::/home/runner/.local/bin"
        echo "-----------"
        pip3 list

    - name: install package
      run: |
        pip3 install --user botocore
        echo "-------"
        pip3 list
        yamllint --version
    
    - name: Setup Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.8.x
        
    - name: Check yamllint
      run: |
        pip3 list
        yamllint --version
        

