name: Test CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Run SQL Server
      run: |
        Get-ChildItem "C:\Program Files\Microsoft SQL Server\130\Tools\Binn"


