name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        C:\msys64\mingw64\bin\gcc -o sample sample.c
