name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: path
      run: |
        echo $PATH
      
    - name: check openssl
      run: |
        openssl version
        openssl version -d
        ls /usr/local/opt/openssl/lib
        echo "-------"
        brew info openssl
        echo "-------"
        brew switch openssl 1.0.2t
        echo "-------"
        brew info openssl
    
    - name: install automake
      shell: bash
      run: |
        curl -O -L http://ftpmirror.gnu.org/automake/automake-1.16.2.tar.gz
        tar -xzf automake-1.16.2.tar.gz
        cd ./automake-1.16.2
        ./configure
        make
        sudo make install
        echo "-----------------------"
        automake --version
  
    - name: build
      run: |
        bash ./test.sh
        
