name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Test
      run: |
        echo "::set-env name={SDKROOT}::{C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk}"
        copy "$env:SDKROOT\usr\share\ucrt.modulemap" "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
        copy "$env:SDKROOT\usr\share\visualc.modulemap" "%VCToolsInstallDir%\include\module.modulemap"
        copy "$env:SDKROOT\usr\share\visualc.apinotes" "%VCToolsInstallDir%\include\visualc.apinotes"
        copy "$env:SDKROOT\usr\share\winsdk.modulemap" "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
        pwsh ./Test.ps1


