name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: path
      run: |
        echo $PATH
        find /usr/local/bin -type l -ls
      
    - name: check openssl
      run: |
        openssl version
        openssl version -d
        echo "----"
        ls -la /usr/local/etc
    
    - name: install openssl 1.1
      run: |
        ls -al /usr/local/Cellar/openssl*
        brew switch openssl 1.0.2t
        brew switch openssl@1.1 1.1.1g
    
    - name: check openssl
      run: |
        openssl version
        openssl version -d
    
    
    - name: Test.ps1
      run: |
        pwsh Test.ps1
        
