name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Test.ps1
      run: |
        pwsh Test.ps1
        
