name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    
    - name: Help
      run: |
        flex --help
        echo "-------"
        cc --help
    
    - name: Test
      run: |
        flex sample.lex
        bison -dt sample.y
        cc lex.yy.c sample.tab.c
        ./a.out
        



