name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        wget "https://www.microsoft.com/en-us/download/confirmation.aspx?id=7030"
