name: Test CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Create pull request
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Test",
            head: "test-approve",
            base: "master",
            body: `hello \ world`
          });


