name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: path
      run: |
        echo $PATH
      
    - name: check openssl
      run: |
        openssl version
        openssl version -d
    
#     - name: install openssl 1.1
#       run: |
#         ln -sf /usr/local/Cellar/openssl@1.1/1.1.1g /usr/local/Cellar/openssl
#         ln -sf /usr/local/Cellar/openssl/1.1.1g/bin/openssl /usr/local/bin/openssl
#         rm /usr/local/opt/openssl
#         ln -sf /usr/local/Cellar/openssl/1.1.1g /usr/local/opt/openssl
#         ls /usr/local/Cellar/openssl
    
    - name: install automake
      run: brew install automake
  
    - name: check openssl
      run: |
        openssl version
        openssl version -d

        
