name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: ssh-keyscan
      if: ${{ always() }}
      run: |
        dig +short github.com
        echo "-----"
        ssh-keyscan -t rsa github.com
        echo "-----"
        ssh-keyscan -t rsa gist.github.com
        echo "-----"
        cat .ssh/known_hosts
        cat /etc/ssh/ssh_known_hosts
    
    - name: ssh
      if: ${{ always() }}
      run: |
        echo 'hello'
    
    - name: known hosts
      if: ${{ always() }}
      run: |
        cat .ssh/known_hosts
        cat /etc/ssh/ssh_known_hosts
        
    - name: Test
      run: |
        pwsh ./Test.ps1


