name: Test CI

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: pipx install
      run: |
        export PIPX_BIN_DIR=/opt/pipx_bin
        export PIPX_HOME=/opt/pipx
        brew install pipx
        sudo pipx ensurepath
        
