name: Test CI

on:
  workflow_dispatch:
    inputs:
      subscriptionID:
        description: 'Azure subscription id'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        git clone https://github.com/actions/virtual-environments.git
        cd C:\virtual-environments
        Import-Module "helpers\GenerateResourcesAndImage.ps1"
        GenerateResourcesAndImage -SubscriptionId ${{ github.event.inputs.logLevel }} -ResourceGroupName "v-vlsafo" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1604 -AzureLocation "East US"


