name: Test Python 3.7 on Ubuntu container 18.04

on:
  workflow_dispatch:

jobs:
  tests:
    container:
      image: ubuntu:18.04
    runs-on: ubuntu-18.04 

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Check python
      run: |
        python --version
        which python
        ldd --version

    - name: Install wget
      run: |
        apt-get update
        apt-get install wget -y

    - name: Install dev dependencies & build package
      run: |
        wget -qO- https://bootstrap.pypa.io/get-pip.py | python