name: gcc

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - gcc

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: where gcc
      shell: pwsh
      run: (Get-Command gcc).Source
    
    - name: ls bin
      run: ls -la /usr/bin | grep "gcc"

    - name: Test
      run: |
        export CFLAGS='--disable-werror'
        gcc -v -o hello hello.c
