name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: dotnet --info

    - name: Install dotnet (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: bash ./dotnet-installers/install-dotnet.sh --channel 3.0
    
    - name: Install dotnet (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: pwsh ./dotnet-installers/install-dotnet.ps1 -Channel 3.0

    - run: echo $PATH

    - run: dotnet --info

    
