name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - run: ls -la /usr/local/opt/runner/settings
    - run: cat /usr/local/opt/runner/settings/778164636A7E9040C51F9CD3F5FC1FF2FD4ABED5.pfx


