name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Create pull request for ${{ github.event.client_payload.ReleaseBranchName }}
      id: create-pr
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let response = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Test PR",
            head: "gcc",
            base: "master",
            body: `PR description`
          })
          return response.data.number
        
    - name: Request reviewers
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.TEST_TOKEN}}
        script: |
          github.pulls.requestReviewers({
              owner: 'actions',
              repo: 'virtual-environments',
              pull_number: 3963,
              team_reviewers: ['virtual-environments-akvelon']
          });
     




