name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - run: Get-ChildItem 'C:\Program Files\Microsoft Visual Studio'
#     - run:  vcpkg --version
#     - run: |
#         Remove-Item "C:\vcpkg" -Recurse -Force
#     - run: |
#         $Uri = 'https://github.com/Microsoft/vcpkg.git'
#         $InstallDir = 'C:\vcpkg'
#         $VcpkgExecPath = 'vcpkg.exe'
#         git clone $Uri $InstallDir -q
#         Push-Location $InstallDir
#         git checkout 71422c627264daedcbcd46f01f1ed0dcd8460f1b
#         Pop-Location
#         Invoke-Expression "$InstallDir\bootstrap-vcpkg.bat"
#         Invoke-Expression "$InstallDir\$VcpkgExecPath integrate install"
#     - run: vcpkg --version
  
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
        
#     - uses: actions/cache@v2
#       with:
#         path: ~/.cache/pip
#         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

#     - name: downgrade chromedriver
#       run: |
#         CHROMEDRIVER_DIR="/usr/local/share/chrome_driver"
#         CHROMEDRIVER_BIN="$CHROMEDRIVER_DIR/chromedriver"
#         sudo rm -rf $CHROMEDRIVER_DIR
#         curl https://chromedriver.storage.googleapis.com/93.0.4577.15/chromedriver_linux64.zip -4 -sL -o ~/chromedriver_linux64.zip
#         sudo mkdir -p $CHROMEDRIVER_DIR
#         sudo unzip ~/chromedriver_linux64.zip -d $CHROMEDRIVER_DIR
#         sudo chmod +x $CHROMEDRIVER_BIN
    
    

     




