name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master
      - v-vlsafo/macos-gradle

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: gradle --version
    
    - name: Test
      run: |
        ls -la /tmp
        echo "---------------"
        cd /tmp && gradle tasks
        
    - name: update gradle
      run: |
        brew update
        brew upgrade gradle

    - run: gradle --version

    - name: Test
      run: |
        cd / && sudo touch settings.gradle && gradle tasks

