name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        ls -la "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current"
