name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master
      - v-vlsafo/macos-gradle

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: gradle --version
    
    - name: Test
      run: |
        cd /tmp && gradle tasks
        
    - name: Upgrade gradle
      run: |
        brew uninstall gradle
        brew install gradle@7.0.0

    - run: gradle --version

