name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
#     - name: Setup dotnet
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 6.0.x
#         include-prerelease: true
        
#     - name: Setup Go environment
#       uses: actions/setup-go@v2.1.4
#       with:
#         go-version: "1.16.x"
 
    - run: Get-ChildItem "C:\msys64\mingw64\lib"
    - run: |
        cabal update
        cabal install haskell-say -v
        cabal build
        cabal run

#     - run: cabal install --help
#     - run: cabal build --help
#     - run: Get-ChildItem "C:\msys64\mingw64"
#     - run: Get-ChildItem "C:\msys64\mingw64\include"
#     - run: Get-ChildItem "C:\msys64\mingw64\lib"
  
#     - run: echo $PATH

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: pypy-3.x
        
#     - run: echo $PATH
#     - run: echo $pythonLocation
#     - run: ls -la /opt/hostedtoolcache/Python/3.9.10/x64
    
    

     




