name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - run: df -h
    
    - run: ls -la /usr/local/opt/runner/settings
    - run: ls -la /usr/local/opt/runner/settings/warmup
    - run: ls -la /usr/local/opt/runner/settings/factory
    - run: cat /Users/runner/.bashrc


