name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - run: dotnet --version
    
#     - name: Setup dotnet
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '3.1.x'
    
#     - name: Setup dotnet
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '2.2.x'
    - name: Force 3.1.x
      run: | 
        echo "{ \"sdk\": { \"version\": \"3.1\"} }" > global.json
      
    - run: dotnet --version

