name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - test-windows

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: |
        takeown /F "C:\Users\runneradmin\AppData\Local\Application Data"
        icacls "C:\Users\runneradmin\AppData\Local\Application Data" /grant:r administrators:F
        icacls "C:\Users\runneradmin\AppData\Local\Application Data"
        Set-Location "C:\Users\runneradmin\AppData\Local\Application Data"
        Get-Location
        Get-ChildItem . -Force -Recurse -erroraction SilentlyContinue