name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    # - run: ls -la /usr/include/x86_64-linux-gnu/c++
    # - run: sudo rm -rf /usr/include/x86_64-linux-gnu
    # - run: sudo apt-get purge -y libc++abi-11-dev libc++-11-dev && sudo apt-get install -y libc++abi-dev libc++-dev
    - name: build
      run: |
        # export CPLUS_INCLUDE_PATH=/usr/include/c++/11:/usr/include/x86_64-linux-gnu/c++/11
        clang++-11 -stdlib=libc++ test.cpp -o test -v

    - run: ./test
    
