name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: install pipx
      run: |
        python3 -m pip install pipx
        python3 -m pipx ensurepath

    - name: run Test.ps1
      run: |
        pipx --version
        pwsh Test.ps1
