name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master
  schedule:
    - cron: 5 * * * *

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2

#     - name: Setup dotnet
#       uses: actions/setup-dotnet@v1
#       with:
#         source-url: https://api.nuget.org/v3/index.json
#       env:
#         NUGET_AUTH_TOKEN: NOTATOKEN
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASS }}
        login-server: https://testconnection.azurecr.io
        
    - name: pull image from ACR
      run: docker pull testconnection.azurecr.io/testacrconnection:v1
