name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: clang++ -v
    - run: ls -la /usr/include

    - name: build
      run: |
        clang++ -stdlib=libc++ -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 test.cpp -o test -v

    - run: ./test
    
