name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: C:\msys64\mingw32\bin\gcc --version
    
    - name: compile helloworld.c
      run: |
        C:\msys64\mingw32\bin\gcc -v -mtune=core2 -march=nocona helloworld.c -o helloworld
