name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Remove mssql cmd tools
      run: |
        sudo apt-get remove mssql-tools unixodbc-dev
        
    - name: Test
      run: |
        sudo bash ./mssql-cmd-tools.sh
