name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Install dotnet
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: ./dotnet-installers/dotnet-install.sh

    - run: dotnet --info

    
