name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: NOTATOKEN
      
    - run: dotnet --version
    
    - name: Verify nuget config file
      shell: pwsh
      run: |
        if (Test-Path "../nuget.config") { Get-Content "../nuget.config" }
