name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      # matrix:
      #   os:
      #     - 'centos:7'
      #   python:
      #     - '3.7'
      #     - '3.8'
      #     - '3.9'
      #     - '3.10'
        # python-version: [ '3.8.1', '3.7.5', '3.5.4' ]
    # name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
  
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # - name: Setup NodeJS
    #   uses: actions/setup-node@main
    #   with:
    #     node-version-file: 'package.json'

    # - run: node --version

    # - run: echo $RUNNER_OS
    # - run: Get-Command pipx
    # - run: Remove-Item -Force -Recurse 'C:\hostedtoolcache\windows\Python\3.10.5'

    # - run: ls -la /opt/hostedtoolcache/Python


    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        check-latest: true

    - run: python --version   
