name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]

    steps:
    - uses: actions/checkout@v2
    # - run: dotnet new globaljson --sdk-version 3.1.403
    # - run: dotnet --version
    - run: ls
    # - run: ls -la /usr/include/x86_64-linux-gnu/c++
    # - run: sudo rm -rf /usr/include/x86_64-linux-gnu
    # - run: sudo apt-get purge -y libc++abi-11-dev libc++-11-dev && sudo apt-get install -y libc++abi-dev libc++-dev
    # - run: sudo apt-get purge -y g++-7 g++-8 g++-9 g++-10
    # - name: build
    #   run: |
    #     clang++ -stdlib=libc++ test.cpp -o test -v

    # - run: ./test
    
