name: master

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASS }}
        login-server: https://testconnection.azurecr.io
        
    - name: pull image from ACR
      run: docker pull testconnection.azurecr.io/testacrconnection:v1
