name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Test
      shell: pwsh
      run: |
        $dotnet = Get-Command dotnet | Select-Object -First 1 | ForEach-Object { $_.Path }
        Write-Host "Found '$dotnet'"
        $version = & $dotnet --version | Out-String | ForEach-Object { $_.Trim() }
        Write-Host "Version $version"
