name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Test pipx
      run: |
        pipx list
        pipx install pycowsay
        pipx list
        pycowsay hello

