name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: ls -la /usr/local/include
    - run: ls -la /usr/lib/llvm-10/lib/clang/10.0.0/include
    - run: ls -la /usr/include/x86_64-linux-gnu
    - run: ls -la /usr/include

    - name: build
      run: |
        clang++ -stdlib=libc++ test.cpp -o test -v

    - run: ./test
    
