name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - run: azcopy copy --help
    - run: azcopy copy https://vlsafosbttest.blob.core.windows.net/sbtissueartifact/Artifacts.zip ~/test
    - run: ls ~/test
    
    - run: ls -la /opt/runner/provisioner/etc
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

#     - name: downgrade chromedriver
#       run: |
#         CHROMEDRIVER_DIR="/usr/local/share/chrome_driver"
#         CHROMEDRIVER_BIN="$CHROMEDRIVER_DIR/chromedriver"
#         sudo rm -rf $CHROMEDRIVER_DIR
#         curl https://chromedriver.storage.googleapis.com/93.0.4577.15/chromedriver_linux64.zip -4 -sL -o ~/chromedriver_linux64.zip
#         sudo mkdir -p $CHROMEDRIVER_DIR
#         sudo unzip ~/chromedriver_linux64.zip -d $CHROMEDRIVER_DIR
#         sudo chmod +x $CHROMEDRIVER_BIN

    - run: |
        pip install -r requirements.txt
        
    - run: tox --version
    
    

     




