name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15, macos-11 ]

    steps:
    - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: ""
    - name: install python2
      shell: pwsh
      run: |
        Python2Url="https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg"
        curl $Python2Url --output "/tmp/python2.pkg"
        sudo installer -pkg /tmp/python2.pkg -target /
        pip install --upgrade pip
    - run: pip3 --version
    - run: pip --version
    - run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install poetry==1.1.7
    - run: poetry --version
    
    

     




