name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: add mingw32 to path
      shell: bash
      run: |
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH

    - run: env

    - run: C:\msys64\mingw32\bin\gcc --version
    
    - name: compile helloworld.c
      run: |
        pwsh ./Test.ps1
#        C:\msys64\mingw32\bin\gcc -v helloworld.c -o helloworld
         
