name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        # python-version: [ 'pypy-3.7' ]
# jobs:     
#   go-test:
#     uses: vsafonkin/sample-go/.github/workflows/go.yml@main
#     with:
#       go-version: "1.17.7"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: node --version

    - uses: actions/setup-go@v2
      with:
        go-version: 1.5

    - run: go env GOPATH
    - run: go version

    # - run: ldd --version

    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: '12.22.12'

    # - name: Setup python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.10'

    # - run: python --version
    # - run: python ./sample.py

    # - name: VS components
    #   run: ./Test.ps1

    # - name: Setup Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     cache: 'pipenv'

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    # - name: Install pipenv
    #   run: pipx install pipenv

    # - name: Update Pipfile and Pipfile.lock
    #   run: pipenv update

    # - name: Install dependencies
    #   run: pipenv install --verbose


    # - run: cat Pipfile
    # - run: cat Pipfile.lock

    # - name: Run sample code
    #   run: |
    #     pipenv shell
    #     python ./sample.py

    # - name: Run sample code
    #   run: |
    #     VENV_LOCATION=$(pipenv --venv)
    #     echo $VENV_LOCATION
    #     mv sample.py $VENV_LOCATION/sample.py
    #     cd $VENV_LOCATION
    #     ls -la ./src
    #     python --version
    #     python ./sample.py

    # - name: Run python sample
    #   run: python ./sample.py
        
    # - name: Test 
    #   run: ./Test.ps1
        
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python }}
        
    # - name: venv activate Linux
    #   if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
    #   run: |
    #     mkdir test-venv
    #     cd test-venv
    #     python -m venv .
    #     source ./bin/activate
    #     echo "VIRTUAL_ENV: $VIRTUAL_ENV"
        
    # - name: venv activate Windows
    #   if: ${{ matrix.os == 'windows-latest' }}
    #   run: |
    #     mkdir test-venv
    #     cd test-venv
    #     python -m venv .
    #     ./Scripts/Activate.ps1
    #     Write-Host "VIRTUAL_ENV: $env:VIRTUAL_ENV"
        

    # - name: Setup dotnet from global.json
    #   uses: actions/setup-dotnet@v2
        
    # - name: Setup dotnet multiple lines
    #   uses: actions/setup-dotnet@430f78fc13b1169a1f62d84a45dcf6816eb95fca
    #   with:
    #     dotnet-version: |
    #       3.1.*
    #       5.0
          
    # - name: Setup dotnet prerelease
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: "7.0"
    #     include-prerelease: true
          
    # - run: dotnet --info
    
    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: '17'
        
    # - name: Setup Go environment
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: '>=1.17.0'
        
    # - run: go version
        
    # - run: cp -f `which go` /usr/bin/go
    # - run: sudo go version        
