name: master

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11 ]

    steps:
    - uses: actions/checkout@v2
    
    - run: |
        set -e
        git clone https://github.com/miketimofeev/jaxlib-gha-minimal-failing-example.git
        cd jaxlib-gha-minimal-failing-example
        brew install python3
        python3 -m pip --no-cache-dir install --upgrade pip setuptools wheel
        python3 -m pip --no-cache-dir install -r requirements.txt
        python3 -m pip list
        python3 -v debug_64b.py



