name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - run: dotnet --help
    
    - run: dotnet --list-sdks
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.x'

    - name: Force 2.2.207
      run: | 
        dotnet new globaljson --sdk-version "2.2.207"
      
    - run: dotnet --version
    
    - run: dotnet --list-sdks

