name: master

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - master

jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: path
      run: |
        echo $PATH
    
    - name: /usr/local/bin
      run: |
        ls -la /usr/local/bin | grep "openssl"

    - name: /usr/local/opt
      run: |
        ls -la /usr/local/opt | grep "openssl"

    - name: /usr/local/Cellar
      run: |
        ls -la /usr/local/Cellar | grep "openssl"

    - name: uninstall openssl
      run: |
        # cat /usr/local/Homebrew/Library/Taps/local/homebrew-openssl/Formula/openssl@1.0.2t.rb
        brew uninstall openssl
        rm -rf /usr/local/etc/openssl
        brew uninstall openssl
        
    
    - name: /usr/local/opt
      run: |
        ls -la /usr/local/opt | grep "openssl"
    
    - name: /usr/local/Cellar
      run: |
        ls -la /usr/local/Cellar | grep "openssl"

    - name: /usr/local/bin
      run: |
        ls -la /usr/local/bin | grep "openssl"

    - name: check openssl version
      run: |
        openssl version
        
    - name: run Test.ps1
      run: |
        pwsh Test.ps1
