name: openssl

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - openssl/couchbase-shell

jobs:
  run_Test_ps1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: path
      run: |
        echo $PATH
      
    - name: check openssl
      run: |
        
        ls -la /usr/local/opt | grep "openssl"
        rm -f /usr/local/opt/openssl@1.1
    
    - name: install automake
      shell: bash
      run: |
        brew install automake
  
    - name: build
      run: |
        bash ./test.sh
        
