name: openssl/couchbase-shell

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - openssl/couchbase-shell

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: path
      run: |
        echo $PATH
      
    - name: fix openssl
      run: |
        rm -rf /usr/local/Cellar/openssl
        ln -sf /usr/local/Cellar/openssl@1.0.2t/1.0.2t /usr/local/opt/openssl
        ln -sf /usr/local/Cellar/openssl@1.0.2t/1.0.2t/bin/openssl /usr/local/bin/openssl
    
    - name: install automake
      run: |
        brew install automake
  
    - name: build
      run: |
        bash ./test.sh
        
