name: python

on:
  push:
    branches: [ python ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run test.py
        run: |
          pip3 install requests
          python3 test.py
          
      - name: log
        run: cat python_log.txt
