name: Install Swift 5.3 on Windows

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'

jobs:
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Swift 5.3
        run: |
          Get-PSDrive
          Install-Binary -Url "https://github.com/compnerd/swift-build/releases/latest/download/installer.exe" -Name "installer.exe" -ArgumentList ("-q")
          Get-PSDrive
          
      - name: Set env variables
        run: |
          echo "::set-env name=SDKROOT::C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk"
          echo "::add-path::C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin"
          echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja"

      - name: Check version
        run: swift --version
      
      - name: Test build
        run: |
          git clone git://github.com/compnerd/swift-cmake-examples C:\swift-cmake-examples
          $SWIFTFLAGS="-sdk $env:SDKROOT -resource-dir $env:SDKROOT/usr/lib/swift -I $env:SDKROOT/usr/lib/swift -L $env:SDKROOT/usr/lib/swift/windows"
          cmake -B "C:\HelloWorld" -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -D CMAKE_Swift_FLAGS=$SWIFTFLAGS -G Ninja -S "C:\swift-cmake-examples\HelloWorld"
          cmake --build C:\HelloWorld
