name: xcode-command-line-tools

on:
  workflow_dispatch:
    inputs:
      testParam:
        description: 'Test parameter'     
        required: true
        default: '1'
  push:
    branches:
      - xcode-command-line-tools

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: check xcltools dir
      run: |
        clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
        sudo touch $clt_placeholder
        softwareupdate -l
        sudo rm -rf /Library/Developer/CommandLineTools
        softwareupdate -l

    - name: run test.sh
      run: |
        bash ./test.sh
